version: "3"
services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trace_db
    volumes:
      - ./trace-database/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql